# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
    groups:
      gh-dependency:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "."
    schedule:
      interval: "monthly"
    groups:
      go-dependency:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "./docker"
    schedule:
      interval: "monthly"
    groups:
      docker-dependency:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "./docker"
    schedule:
      interval: "monthly"
    groups:
      docker-compose-dependency:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "./ui"
    schedule:
      interval: "monthly"
    groups:
      npm-dependency:
        patterns:
          - "*"
