File = "config.toml"
domain_id = ""

[channels]
  id = ""

[nodered]
  url = "http://localhost:1880/"

[heartbeat]
  interval = "10s"

[log]
  level = "info"

[mqtt]
  ca_cert = ""
  ca_path = "ca.crt"
  cert_path = "client.cert"
  client_cert = ""
  client_key = ""
  mtls = false
  password = ""
  priv_key_path = "client.key"
  qos = 0
  retain = false
  skip_tls_ver = false
  url = "tcp://localhost:1883"
  username = ""

[server]
  broker_url = "amqp://guest:guest@localhost:5682/"
  port = "9999"

[terminal]
  session_timeout = "60s"
