// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/agent/pkg/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddConfig provides a mock function for the type Service
func (_mock *Service) AddConfig(config agent.Config) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for AddConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(agent.Config) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_AddConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfig'
type Service_AddConfig_Call struct {
	*mock.Call
}

// AddConfig is a helper method to define mock.On call
//   - config agent.Config
func (_e *Service_Expecter) AddConfig(config interface{}) *Service_AddConfig_Call {
	return &Service_AddConfig_Call{Call: _e.mock.On("AddConfig", config)}
}

func (_c *Service_AddConfig_Call) Run(run func(config agent.Config)) *Service_AddConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 agent.Config
		if args[0] != nil {
			arg0 = args[0].(agent.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_AddConfig_Call) Return(err error) *Service_AddConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_AddConfig_Call) RunAndReturn(run func(config agent.Config) error) *Service_AddConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type Service
func (_mock *Service) Config() agent.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 agent.Config
	if returnFunc, ok := ret.Get(0).(func() agent.Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agent.Config)
	}
	return r0
}

// Service_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type Service_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *Service_Expecter) Config() *Service_Config_Call {
	return &Service_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *Service_Config_Call) Run(run func()) *Service_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Config_Call) Return(config agent.Config) *Service_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *Service_Config_Call) RunAndReturn(run func() agent.Config) *Service_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Control provides a mock function for the type Service
func (_mock *Service) Control(s string, s1 string) error {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Control")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Control_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Control'
type Service_Control_Call struct {
	*mock.Call
}

// Control is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *Service_Expecter) Control(s interface{}, s1 interface{}) *Service_Control_Call {
	return &Service_Control_Call{Call: _e.mock.On("Control", s, s1)}
}

func (_c *Service_Control_Call) Run(run func(s string, s1 string)) *Service_Control_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Control_Call) Return(err error) *Service_Control_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Control_Call) RunAndReturn(run func(s string, s1 string) error) *Service_Control_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type Service
func (_mock *Service) Execute(s string, s1 string) (string, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Service_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *Service_Expecter) Execute(s interface{}, s1 interface{}) *Service_Execute_Call {
	return &Service_Execute_Call{Call: _e.mock.On("Execute", s, s1)}
}

func (_c *Service_Execute_Call) Run(run func(s string, s1 string)) *Service_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Execute_Call) Return(s2 string, err error) *Service_Execute_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *Service_Execute_Call) RunAndReturn(run func(s string, s1 string) (string, error)) *Service_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NodeRed provides a mock function for the type Service
func (_mock *Service) NodeRed(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for NodeRed")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_NodeRed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeRed'
type Service_NodeRed_Call struct {
	*mock.Call
}

// NodeRed is a helper method to define mock.On call
//   - s string
func (_e *Service_Expecter) NodeRed(s interface{}) *Service_NodeRed_Call {
	return &Service_NodeRed_Call{Call: _e.mock.On("NodeRed", s)}
}

func (_c *Service_NodeRed_Call) Run(run func(s string)) *Service_NodeRed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_NodeRed_Call) Return(s1 string, err error) *Service_NodeRed_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *Service_NodeRed_Call) RunAndReturn(run func(s string) (string, error)) *Service_NodeRed_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Service
func (_mock *Service) Publish(s string, s1 string) error {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Service_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *Service_Expecter) Publish(s interface{}, s1 interface{}) *Service_Publish_Call {
	return &Service_Publish_Call{Call: _e.mock.On("Publish", s, s1)}
}

func (_c *Service_Publish_Call) Run(run func(s string, s1 string)) *Service_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Publish_Call) Return(err error) *Service_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Publish_Call) RunAndReturn(run func(s string, s1 string) error) *Service_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceConfig provides a mock function for the type Service
func (_mock *Service) ServiceConfig(ctx context.Context, uuid string, cmdStr string) error {
	ret := _mock.Called(ctx, uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for ServiceConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ServiceConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceConfig'
type Service_ServiceConfig_Call struct {
	*mock.Call
}

// ServiceConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) ServiceConfig(ctx interface{}, uuid interface{}, cmdStr interface{}) *Service_ServiceConfig_Call {
	return &Service_ServiceConfig_Call{Call: _e.mock.On("ServiceConfig", ctx, uuid, cmdStr)}
}

func (_c *Service_ServiceConfig_Call) Run(run func(ctx context.Context, uuid string, cmdStr string)) *Service_ServiceConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_ServiceConfig_Call) Return(err error) *Service_ServiceConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ServiceConfig_Call) RunAndReturn(run func(ctx context.Context, uuid string, cmdStr string) error) *Service_ServiceConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function for the type Service
func (_mock *Service) Services() []agent.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []agent.Info
	if returnFunc, ok := ret.Get(0).(func() []agent.Info); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agent.Info)
		}
	}
	return r0
}

// Service_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type Service_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
func (_e *Service_Expecter) Services() *Service_Services_Call {
	return &Service_Services_Call{Call: _e.mock.On("Services")}
}

func (_c *Service_Services_Call) Run(run func()) *Service_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Services_Call) Return(infos []agent.Info) *Service_Services_Call {
	_c.Call.Return(infos)
	return _c
}

func (_c *Service_Services_Call) RunAndReturn(run func() []agent.Info) *Service_Services_Call {
	_c.Call.Return(run)
	return _c
}

// Terminal provides a mock function for the type Service
func (_mock *Service) Terminal(s string, s1 string) error {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Terminal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Terminal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminal'
type Service_Terminal_Call struct {
	*mock.Call
}

// Terminal is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *Service_Expecter) Terminal(s interface{}, s1 interface{}) *Service_Terminal_Call {
	return &Service_Terminal_Call{Call: _e.mock.On("Terminal", s, s1)}
}

func (_c *Service_Terminal_Call) Run(run func(s string, s1 string)) *Service_Terminal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Terminal_Call) Return(err error) *Service_Terminal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Terminal_Call) RunAndReturn(run func(s string, s1 string) error) *Service_Terminal_Call {
	_c.Call.Return(run)
	return _c
}
