# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0
# Do not use docker if using remote terminal

version: "3.7"

networks:
  docker_magistrala-base-net:
    external: true

volumes:
  magistrala-agent-volume:

services:
  magistrala-agent:
    image: magistrala/agent:latest
    container_name: magistrala-agent
    restart: on-failure
    environment:
      MG_AGENT_BOOTSTRAP_ID: ${MG_AGENT_BOOTSTRAP_ID}
      MG_AGENT_BOOTSTRAP_KEY: ${MG_AGENT_BOOTSTRAP_KEY}
      MG_AGENT_BOOTSTRAP_URL: ${MG_AGENT_BOOTSTRAP_URL}
    ports:
      - ${MG_AGENT_PORT}:${MG_AGENT_PORT}
    networks:
      - docker_magistrala-base-net
    volumes:
      - ../configs/config.toml:/config.toml
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
