# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

networks:
  magistrala-agent-base-net:
    driver: bridge

volumes:
  nodered-data:
  fluxmq-data:

services:
  fluxmq:
    image: ghcr.io/absmach/fluxmq:latest
    container_name: agent-fluxmq
    restart: on-failure
    user: "0:0"
    command: ["-config", "/etc/fluxmq/config.yaml"]
    ports:
      - "5692:5682"
    networks:
      - magistrala-agent-base-net
    volumes:
      - ./fluxmq/config.yaml:/etc/fluxmq/config.yaml:ro
      - fluxmq-data:/tmp/fluxmq

  nodered:
    image: nodered/node-red:latest
    container_name: agent-nodered
    restart: on-failure
    entrypoint: ["/seed/entrypoint.sh"]
    ports:
      - "1880:1880"
    networks:
      - magistrala-agent-base-net
    volumes:
      - ./nodered:/seed:ro
      - nodered-data:/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      TZ: UTC
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      MG_AGENT_CLIENT_ID: ${MG_AGENT_CLIENT_ID}
      MG_AGENT_CLIENT_SECRET: ${MG_AGENT_CLIENT_SECRET}
      MG_AGENT_DOMAIN_ID: ${MG_AGENT_DOMAIN_ID}
      MG_AGENT_CHANNEL: ${MG_AGENT_CHANNEL}
  agent:
    image: ${MG_AGENT_IMAGE}
    container_name: magistrala-agent
    restart: on-failure
    depends_on:
      - fluxmq
      - nodered
    ports:
      - "${MG_AGENT_HTTP_PORT}:${MG_AGENT_HTTP_PORT}"
    networks:
      - magistrala-agent-base-net
    environment:
      MG_AGENT_CONFIG_FILE: /config.toml
      MG_AGENT_LOG_LEVEL: debug
      MG_AGENT_HTTP_PORT: ${MG_AGENT_HTTP_PORT}
      MG_AGENT_MQTT_URL: ${MG_AGENT_MQTT_URL}
      MG_AGENT_MQTT_USERNAME: ${MG_AGENT_CLIENT_ID}
      MG_AGENT_MQTT_PASSWORD: ${MG_AGENT_CLIENT_SECRET}
      MG_AGENT_MQTT_SKIP_TLS: ${MG_AGENT_MQTT_SKIP_TLS}
      MG_AGENT_MQTT_MTLS: ${MG_AGENT_MQTT_MTLS}
      MG_AGENT_CHANNEL: ${MG_AGENT_CHANNEL}
      MG_AGENT_DOMAIN_ID: ${MG_AGENT_DOMAIN_ID}
      MG_AGENT_BROKER_URL: ${MG_AGENT_BROKER_URL}
      MG_AGENT_NODERED_URL: ${MG_AGENT_NODERED_URL}
      MG_AGENT_HEARTBEAT_INTERVAL: ${MG_AGENT_HEARTBEAT_INTERVAL}
      MG_AGENT_TERMINAL_SESSION_TIMEOUT: ${MG_AGENT_TERMINAL_SESSION_TIMEOUT}
    volumes:
      - ../configs/config.toml:/config.toml
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
