// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMQTTToken creates a new instance of MQTTToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMQTTToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MQTTToken {
	mock := &MQTTToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MQTTToken is an autogenerated mock type for the Token type
type MQTTToken struct {
	mock.Mock
}

type MQTTToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MQTTToken) EXPECT() *MQTTToken_Expecter {
	return &MQTTToken_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MQTTToken
func (_mock *MQTTToken) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MQTTToken_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MQTTToken_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MQTTToken_Expecter) Done() *MQTTToken_Done_Call {
	return &MQTTToken_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MQTTToken_Done_Call) Run(run func()) *MQTTToken_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTToken_Done_Call) Return(valCh <-chan struct{}) *MQTTToken_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MQTTToken_Done_Call) RunAndReturn(run func() <-chan struct{}) *MQTTToken_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MQTTToken
func (_mock *MQTTToken) Error() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MQTTToken_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MQTTToken_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MQTTToken_Expecter) Error() *MQTTToken_Error_Call {
	return &MQTTToken_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MQTTToken_Error_Call) Run(run func()) *MQTTToken_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTToken_Error_Call) Return(err error) *MQTTToken_Error_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MQTTToken_Error_Call) RunAndReturn(run func() error) *MQTTToken_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MQTTToken
func (_mock *MQTTToken) Wait() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MQTTToken_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MQTTToken_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MQTTToken_Expecter) Wait() *MQTTToken_Wait_Call {
	return &MQTTToken_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MQTTToken_Wait_Call) Run(run func()) *MQTTToken_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTToken_Wait_Call) Return(b bool) *MQTTToken_Wait_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MQTTToken_Wait_Call) RunAndReturn(run func() bool) *MQTTToken_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// WaitTimeout provides a mock function for the type MQTTToken
func (_mock *MQTTToken) WaitTimeout(duration time.Duration) bool {
	ret := _mock.Called(duration)

	if len(ret) == 0 {
		panic("no return value specified for WaitTimeout")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Duration) bool); ok {
		r0 = returnFunc(duration)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MQTTToken_WaitTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitTimeout'
type MQTTToken_WaitTimeout_Call struct {
	*mock.Call
}

// WaitTimeout is a helper method to define mock.On call
//   - duration time.Duration
func (_e *MQTTToken_Expecter) WaitTimeout(duration interface{}) *MQTTToken_WaitTimeout_Call {
	return &MQTTToken_WaitTimeout_Call{Call: _e.mock.On("WaitTimeout", duration)}
}

func (_c *MQTTToken_WaitTimeout_Call) Run(run func(duration time.Duration)) *MQTTToken_WaitTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MQTTToken_WaitTimeout_Call) Return(b bool) *MQTTToken_WaitTimeout_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MQTTToken_WaitTimeout_Call) RunAndReturn(run func(duration time.Duration) bool) *MQTTToken_WaitTimeout_Call {
	_c.Call.Return(run)
	return _c
}
