// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// NewMQTTClient creates a new instance of MQTTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMQTTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MQTTClient {
	mock := &MQTTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MQTTClient is an autogenerated mock type for the Client type
type MQTTClient struct {
	mock.Mock
}

type MQTTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MQTTClient) EXPECT() *MQTTClient_Expecter {
	return &MQTTClient_Expecter{mock: &_m.Mock}
}

// AddRoute provides a mock function for the type MQTTClient
func (_mock *MQTTClient) AddRoute(topic string, callback mqtt.MessageHandler) {
	_mock.Called(topic, callback)
	return
}

// MQTTClient_AddRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoute'
type MQTTClient_AddRoute_Call struct {
	*mock.Call
}

// AddRoute is a helper method to define mock.On call
//   - topic string
//   - callback mqtt.MessageHandler
func (_e *MQTTClient_Expecter) AddRoute(topic interface{}, callback interface{}) *MQTTClient_AddRoute_Call {
	return &MQTTClient_AddRoute_Call{Call: _e.mock.On("AddRoute", topic, callback)}
}

func (_c *MQTTClient_AddRoute_Call) Run(run func(topic string, callback mqtt.MessageHandler)) *MQTTClient_AddRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 mqtt.MessageHandler
		if args[1] != nil {
			arg1 = args[1].(mqtt.MessageHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MQTTClient_AddRoute_Call) Return() *MQTTClient_AddRoute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_AddRoute_Call) RunAndReturn(run func(topic string, callback mqtt.MessageHandler)) *MQTTClient_AddRoute_Call {
	_c.Run(run)
	return _c
}

// Connect provides a mock function for the type MQTTClient
func (_mock *MQTTClient) Connect() mqtt.Token {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func() mqtt.Token); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MQTTClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MQTTClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MQTTClient_Expecter) Connect() *MQTTClient_Connect_Call {
	return &MQTTClient_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MQTTClient_Connect_Call) Run(run func()) *MQTTClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTClient_Connect_Call) Return(token mqtt.Token) *MQTTClient_Connect_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MQTTClient_Connect_Call) RunAndReturn(run func() mqtt.Token) *MQTTClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MQTTClient
func (_mock *MQTTClient) Disconnect(quiesce uint) {
	_mock.Called(quiesce)
	return
}

// MQTTClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MQTTClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - quiesce uint
func (_e *MQTTClient_Expecter) Disconnect(quiesce interface{}) *MQTTClient_Disconnect_Call {
	return &MQTTClient_Disconnect_Call{Call: _e.mock.On("Disconnect", quiesce)}
}

func (_c *MQTTClient_Disconnect_Call) Run(run func(quiesce uint)) *MQTTClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MQTTClient_Disconnect_Call) Return() *MQTTClient_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_Disconnect_Call) RunAndReturn(run func(quiesce uint)) *MQTTClient_Disconnect_Call {
	_c.Run(run)
	return _c
}

// IsConnected provides a mock function for the type MQTTClient
func (_mock *MQTTClient) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MQTTClient_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MQTTClient_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MQTTClient_Expecter) IsConnected() *MQTTClient_IsConnected_Call {
	return &MQTTClient_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MQTTClient_IsConnected_Call) Run(run func()) *MQTTClient_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTClient_IsConnected_Call) Return(b bool) *MQTTClient_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MQTTClient_IsConnected_Call) RunAndReturn(run func() bool) *MQTTClient_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnectionOpen provides a mock function for the type MQTTClient
func (_mock *MQTTClient) IsConnectionOpen() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnectionOpen")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MQTTClient_IsConnectionOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnectionOpen'
type MQTTClient_IsConnectionOpen_Call struct {
	*mock.Call
}

// IsConnectionOpen is a helper method to define mock.On call
func (_e *MQTTClient_Expecter) IsConnectionOpen() *MQTTClient_IsConnectionOpen_Call {
	return &MQTTClient_IsConnectionOpen_Call{Call: _e.mock.On("IsConnectionOpen")}
}

func (_c *MQTTClient_IsConnectionOpen_Call) Run(run func()) *MQTTClient_IsConnectionOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTClient_IsConnectionOpen_Call) Return(b bool) *MQTTClient_IsConnectionOpen_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MQTTClient_IsConnectionOpen_Call) RunAndReturn(run func() bool) *MQTTClient_IsConnectionOpen_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsReader provides a mock function for the type MQTTClient
func (_mock *MQTTClient) OptionsReader() mqtt.ClientOptionsReader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OptionsReader")
	}

	var r0 mqtt.ClientOptionsReader
	if returnFunc, ok := ret.Get(0).(func() mqtt.ClientOptionsReader); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(mqtt.ClientOptionsReader)
	}
	return r0
}

// MQTTClient_OptionsReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsReader'
type MQTTClient_OptionsReader_Call struct {
	*mock.Call
}

// OptionsReader is a helper method to define mock.On call
func (_e *MQTTClient_Expecter) OptionsReader() *MQTTClient_OptionsReader_Call {
	return &MQTTClient_OptionsReader_Call{Call: _e.mock.On("OptionsReader")}
}

func (_c *MQTTClient_OptionsReader_Call) Run(run func()) *MQTTClient_OptionsReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTClient_OptionsReader_Call) Return(clientOptionsReader mqtt.ClientOptionsReader) *MQTTClient_OptionsReader_Call {
	_c.Call.Return(clientOptionsReader)
	return _c
}

func (_c *MQTTClient_OptionsReader_Call) RunAndReturn(run func() mqtt.ClientOptionsReader) *MQTTClient_OptionsReader_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MQTTClient
func (_mock *MQTTClient) Publish(topic string, qos byte, retained bool, payload interface{}) mqtt.Token {
	ret := _mock.Called(topic, qos, retained, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(string, byte, bool, interface{}) mqtt.Token); ok {
		r0 = returnFunc(topic, qos, retained, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MQTTClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MQTTClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - retained bool
//   - payload interface{}
func (_e *MQTTClient_Expecter) Publish(topic interface{}, qos interface{}, retained interface{}, payload interface{}) *MQTTClient_Publish_Call {
	return &MQTTClient_Publish_Call{Call: _e.mock.On("Publish", topic, qos, retained, payload)}
}

func (_c *MQTTClient_Publish_Call) Run(run func(topic string, qos byte, retained bool, payload interface{})) *MQTTClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MQTTClient_Publish_Call) Return(token mqtt.Token) *MQTTClient_Publish_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MQTTClient_Publish_Call) RunAndReturn(run func(topic string, qos byte, retained bool, payload interface{}) mqtt.Token) *MQTTClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MQTTClient
func (_mock *MQTTClient) Subscribe(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _mock.Called(topic, qos, callback)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = returnFunc(topic, qos, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MQTTClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MQTTClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - callback mqtt.MessageHandler
func (_e *MQTTClient_Expecter) Subscribe(topic interface{}, qos interface{}, callback interface{}) *MQTTClient_Subscribe_Call {
	return &MQTTClient_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, qos, callback)}
}

func (_c *MQTTClient_Subscribe_Call) Run(run func(topic string, qos byte, callback mqtt.MessageHandler)) *MQTTClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 mqtt.MessageHandler
		if args[2] != nil {
			arg2 = args[2].(mqtt.MessageHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MQTTClient_Subscribe_Call) Return(token mqtt.Token) *MQTTClient_Subscribe_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MQTTClient_Subscribe_Call) RunAndReturn(run func(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token) *MQTTClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeMultiple provides a mock function for the type MQTTClient
func (_mock *MQTTClient) SubscribeMultiple(filters map[string]byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _mock.Called(filters, callback)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeMultiple")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(map[string]byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = returnFunc(filters, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MQTTClient_SubscribeMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeMultiple'
type MQTTClient_SubscribeMultiple_Call struct {
	*mock.Call
}

// SubscribeMultiple is a helper method to define mock.On call
//   - filters map[string]byte
//   - callback mqtt.MessageHandler
func (_e *MQTTClient_Expecter) SubscribeMultiple(filters interface{}, callback interface{}) *MQTTClient_SubscribeMultiple_Call {
	return &MQTTClient_SubscribeMultiple_Call{Call: _e.mock.On("SubscribeMultiple", filters, callback)}
}

func (_c *MQTTClient_SubscribeMultiple_Call) Run(run func(filters map[string]byte, callback mqtt.MessageHandler)) *MQTTClient_SubscribeMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]byte
		if args[0] != nil {
			arg0 = args[0].(map[string]byte)
		}
		var arg1 mqtt.MessageHandler
		if args[1] != nil {
			arg1 = args[1].(mqtt.MessageHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MQTTClient_SubscribeMultiple_Call) Return(token mqtt.Token) *MQTTClient_SubscribeMultiple_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MQTTClient_SubscribeMultiple_Call) RunAndReturn(run func(filters map[string]byte, callback mqtt.MessageHandler) mqtt.Token) *MQTTClient_SubscribeMultiple_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MQTTClient
func (_mock *MQTTClient) Unsubscribe(topics ...string) mqtt.Token {
	var tmpRet mock.Arguments
	if len(topics) > 0 {
		tmpRet = _mock.Called(topics)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(...string) mqtt.Token); ok {
		r0 = returnFunc(topics...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MQTTClient_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MQTTClient_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - topics ...string
func (_e *MQTTClient_Expecter) Unsubscribe(topics ...interface{}) *MQTTClient_Unsubscribe_Call {
	return &MQTTClient_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe",
		append([]interface{}{}, topics...)...)}
}

func (_c *MQTTClient_Unsubscribe_Call) Run(run func(topics ...string)) *MQTTClient_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MQTTClient_Unsubscribe_Call) Return(token mqtt.Token) *MQTTClient_Unsubscribe_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MQTTClient_Unsubscribe_Call) RunAndReturn(run func(topics ...string) mqtt.Token) *MQTTClient_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
