// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/agent"
	"github.com/absmach/agent/pkg/devicemgr"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddConfig provides a mock function for the type Service
func (_mock *Service) AddConfig(config agent.Config) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for AddConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(agent.Config) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_AddConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfig'
type Service_AddConfig_Call struct {
	*mock.Call
}

// AddConfig is a helper method to define mock.On call
//   - config agent.Config
func (_e *Service_Expecter) AddConfig(config interface{}) *Service_AddConfig_Call {
	return &Service_AddConfig_Call{Call: _e.mock.On("AddConfig", config)}
}

func (_c *Service_AddConfig_Call) Run(run func(config agent.Config)) *Service_AddConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 agent.Config
		if args[0] != nil {
			arg0 = args[0].(agent.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_AddConfig_Call) Return(err error) *Service_AddConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_AddConfig_Call) RunAndReturn(run func(config agent.Config) error) *Service_AddConfig_Call {
	_c.Call.Return(run)
	return _c
}

// AddDevice provides a mock function for the type Service
func (_mock *Service) AddDevice(ctx context.Context, name string, extID string, extKey string, ifaceType string, ifaceAddr string) (devicemgr.Device, error) {
	ret := _mock.Called(ctx, name, extID, extKey, ifaceType, ifaceAddr)

	if len(ret) == 0 {
		panic("no return value specified for AddDevice")
	}

	var r0 devicemgr.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (devicemgr.Device, error)); ok {
		return returnFunc(ctx, name, extID, extKey, ifaceType, ifaceAddr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) devicemgr.Device); ok {
		r0 = returnFunc(ctx, name, extID, extKey, ifaceType, ifaceAddr)
	} else {
		r0 = ret.Get(0).(devicemgr.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, extID, extKey, ifaceType, ifaceAddr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_AddDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDevice'
type Service_AddDevice_Call struct {
	*mock.Call
}

// AddDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - extID string
//   - extKey string
//   - ifaceType string
//   - ifaceAddr string
func (_e *Service_Expecter) AddDevice(ctx interface{}, name interface{}, extID interface{}, extKey interface{}, ifaceType interface{}, ifaceAddr interface{}) *Service_AddDevice_Call {
	return &Service_AddDevice_Call{Call: _e.mock.On("AddDevice", ctx, name, extID, extKey, ifaceType, ifaceAddr)}
}

func (_c *Service_AddDevice_Call) Run(run func(ctx context.Context, name string, extID string, extKey string, ifaceType string, ifaceAddr string)) *Service_AddDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Service_AddDevice_Call) Return(device devicemgr.Device, err error) *Service_AddDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *Service_AddDevice_Call) RunAndReturn(run func(ctx context.Context, name string, extID string, extKey string, ifaceType string, ifaceAddr string) (devicemgr.Device, error)) *Service_AddDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CloseDevice provides a mock function for the type Service
func (_mock *Service) CloseDevice(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CloseDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_CloseDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDevice'
type Service_CloseDevice_Call struct {
	*mock.Call
}

// CloseDevice is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) CloseDevice(id interface{}) *Service_CloseDevice_Call {
	return &Service_CloseDevice_Call{Call: _e.mock.On("CloseDevice", id)}
}

func (_c *Service_CloseDevice_Call) Run(run func(id string)) *Service_CloseDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_CloseDevice_Call) Return(err error) *Service_CloseDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_CloseDevice_Call) RunAndReturn(run func(id string) error) *Service_CloseDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CommandSecret provides a mock function for the type Service
func (_mock *Service) CommandSecret() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandSecret")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Service_CommandSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandSecret'
type Service_CommandSecret_Call struct {
	*mock.Call
}

// CommandSecret is a helper method to define mock.On call
func (_e *Service_Expecter) CommandSecret() *Service_CommandSecret_Call {
	return &Service_CommandSecret_Call{Call: _e.mock.On("CommandSecret")}
}

func (_c *Service_CommandSecret_Call) Run(run func()) *Service_CommandSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_CommandSecret_Call) Return(s string) *Service_CommandSecret_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Service_CommandSecret_Call) RunAndReturn(run func() string) *Service_CommandSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type Service
func (_mock *Service) Config() agent.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 agent.Config
	if returnFunc, ok := ret.Get(0).(func() agent.Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agent.Config)
	}
	return r0
}

// Service_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type Service_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *Service_Expecter) Config() *Service_Config_Call {
	return &Service_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *Service_Config_Call) Run(run func()) *Service_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Config_Call) Return(config agent.Config) *Service_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *Service_Config_Call) RunAndReturn(run func() agent.Config) *Service_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Control provides a mock function for the type Service
func (_mock *Service) Control(uuid string, cmdStr string) error {
	ret := _mock.Called(uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for Control")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Control_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Control'
type Service_Control_Call struct {
	*mock.Call
}

// Control is a helper method to define mock.On call
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) Control(uuid interface{}, cmdStr interface{}) *Service_Control_Call {
	return &Service_Control_Call{Call: _e.mock.On("Control", uuid, cmdStr)}
}

func (_c *Service_Control_Call) Run(run func(uuid string, cmdStr string)) *Service_Control_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Control_Call) Return(err error) *Service_Control_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Control_Call) RunAndReturn(run func(uuid string, cmdStr string) error) *Service_Control_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceManager provides a mock function for the type Service
func (_mock *Service) DeviceManager(ctx context.Context, uuid string, cmdStr string) error {
	ret := _mock.Called(ctx, uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for DeviceManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_DeviceManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceManager'
type Service_DeviceManager_Call struct {
	*mock.Call
}

// DeviceManager is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) DeviceManager(ctx interface{}, uuid interface{}, cmdStr interface{}) *Service_DeviceManager_Call {
	return &Service_DeviceManager_Call{Call: _e.mock.On("DeviceManager", ctx, uuid, cmdStr)}
}

func (_c *Service_DeviceManager_Call) Run(run func(ctx context.Context, uuid string, cmdStr string)) *Service_DeviceManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_DeviceManager_Call) Return(err error) *Service_DeviceManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_DeviceManager_Call) RunAndReturn(run func(ctx context.Context, uuid string, cmdStr string) error) *Service_DeviceManager_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type Service
func (_mock *Service) Execute(uuid string, cmd string) (string, error) {
	ret := _mock.Called(uuid, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(uuid, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(uuid, cmd)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uuid, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Service_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - uuid string
//   - cmd string
func (_e *Service_Expecter) Execute(uuid interface{}, cmd interface{}) *Service_Execute_Call {
	return &Service_Execute_Call{Call: _e.mock.On("Execute", uuid, cmd)}
}

func (_c *Service_Execute_Call) Run(run func(uuid string, cmd string)) *Service_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Execute_Call) Return(s string, err error) *Service_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Service_Execute_Call) RunAndReturn(run func(uuid string, cmd string) (string, error)) *Service_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevice provides a mock function for the type Service
func (_mock *Service) GetDevice(id string) (devicemgr.Device, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDevice")
	}

	var r0 devicemgr.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (devicemgr.Device, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) devicemgr.Device); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(devicemgr.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevice'
type Service_GetDevice_Call struct {
	*mock.Call
}

// GetDevice is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) GetDevice(id interface{}) *Service_GetDevice_Call {
	return &Service_GetDevice_Call{Call: _e.mock.On("GetDevice", id)}
}

func (_c *Service_GetDevice_Call) Run(run func(id string)) *Service_GetDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetDevice_Call) Return(device devicemgr.Device, err error) *Service_GetDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *Service_GetDevice_Call) RunAndReturn(run func(id string) (devicemgr.Device, error)) *Service_GetDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuntimeConfig provides a mock function for the type Service
func (_mock *Service) GetRuntimeConfig(key string) (string, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetRuntimeConfig")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetRuntimeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuntimeConfig'
type Service_GetRuntimeConfig_Call struct {
	*mock.Call
}

// GetRuntimeConfig is a helper method to define mock.On call
//   - key string
func (_e *Service_Expecter) GetRuntimeConfig(key interface{}) *Service_GetRuntimeConfig_Call {
	return &Service_GetRuntimeConfig_Call{Call: _e.mock.On("GetRuntimeConfig", key)}
}

func (_c *Service_GetRuntimeConfig_Call) Run(run func(key string)) *Service_GetRuntimeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetRuntimeConfig_Call) Return(s string, err error) *Service_GetRuntimeConfig_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Service_GetRuntimeConfig_Call) RunAndReturn(run func(key string) (string, error)) *Service_GetRuntimeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function for the type Service
func (_mock *Service) ListDevices() ([]devicemgr.Device, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []devicemgr.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]devicemgr.Device, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []devicemgr.Device); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]devicemgr.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type Service_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
func (_e *Service_Expecter) ListDevices() *Service_ListDevices_Call {
	return &Service_ListDevices_Call{Call: _e.mock.On("ListDevices")}
}

func (_c *Service_ListDevices_Call) Run(run func()) *Service_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_ListDevices_Call) Return(devices []devicemgr.Device, err error) *Service_ListDevices_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *Service_ListDevices_Call) RunAndReturn(run func() ([]devicemgr.Device, error)) *Service_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeviceSeen provides a mock function for the type Service
func (_mock *Service) MarkDeviceSeen(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeviceSeen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_MarkDeviceSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeviceSeen'
type Service_MarkDeviceSeen_Call struct {
	*mock.Call
}

// MarkDeviceSeen is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) MarkDeviceSeen(id interface{}) *Service_MarkDeviceSeen_Call {
	return &Service_MarkDeviceSeen_Call{Call: _e.mock.On("MarkDeviceSeen", id)}
}

func (_c *Service_MarkDeviceSeen_Call) Run(run func(id string)) *Service_MarkDeviceSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_MarkDeviceSeen_Call) Return(err error) *Service_MarkDeviceSeen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_MarkDeviceSeen_Call) RunAndReturn(run func(id string) error) *Service_MarkDeviceSeen_Call {
	_c.Call.Return(run)
	return _c
}

// NodeRed provides a mock function for the type Service
func (_mock *Service) NodeRed(cmdStr string) (string, error) {
	ret := _mock.Called(cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for NodeRed")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(cmdStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(cmdStr)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cmdStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_NodeRed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeRed'
type Service_NodeRed_Call struct {
	*mock.Call
}

// NodeRed is a helper method to define mock.On call
//   - cmdStr string
func (_e *Service_Expecter) NodeRed(cmdStr interface{}) *Service_NodeRed_Call {
	return &Service_NodeRed_Call{Call: _e.mock.On("NodeRed", cmdStr)}
}

func (_c *Service_NodeRed_Call) Run(run func(cmdStr string)) *Service_NodeRed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_NodeRed_Call) Return(s string, err error) *Service_NodeRed_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Service_NodeRed_Call) RunAndReturn(run func(cmdStr string) (string, error)) *Service_NodeRed_Call {
	_c.Call.Return(run)
	return _c
}

// OTA provides a mock function for the type Service
func (_mock *Service) OTA(ctx context.Context, url string, sha256hex string, size uint64) error {
	ret := _mock.Called(ctx, url, sha256hex, size)

	if len(ret) == 0 {
		panic("no return value specified for OTA")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64) error); ok {
		r0 = returnFunc(ctx, url, sha256hex, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_OTA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTA'
type Service_OTA_Call struct {
	*mock.Call
}

// OTA is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - sha256hex string
//   - size uint64
func (_e *Service_Expecter) OTA(ctx interface{}, url interface{}, sha256hex interface{}, size interface{}) *Service_OTA_Call {
	return &Service_OTA_Call{Call: _e.mock.On("OTA", ctx, url, sha256hex, size)}
}

func (_c *Service_OTA_Call) Run(run func(ctx context.Context, url string, sha256hex string, size uint64)) *Service_OTA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_OTA_Call) Return(err error) *Service_OTA_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_OTA_Call) RunAndReturn(run func(ctx context.Context, url string, sha256hex string, size uint64) error) *Service_OTA_Call {
	_c.Call.Return(run)
	return _c
}

// OTAAbort provides a mock function for the type Service
func (_mock *Service) OTAAbort() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OTAAbort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_OTAAbort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTAAbort'
type Service_OTAAbort_Call struct {
	*mock.Call
}

// OTAAbort is a helper method to define mock.On call
func (_e *Service_Expecter) OTAAbort() *Service_OTAAbort_Call {
	return &Service_OTAAbort_Call{Call: _e.mock.On("OTAAbort")}
}

func (_c *Service_OTAAbort_Call) Run(run func()) *Service_OTAAbort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_OTAAbort_Call) Return(err error) *Service_OTAAbort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_OTAAbort_Call) RunAndReturn(run func() error) *Service_OTAAbort_Call {
	_c.Call.Return(run)
	return _c
}

// OTAFromData provides a mock function for the type Service
func (_mock *Service) OTAFromData(ctx context.Context, data []byte, sha256hex string) error {
	ret := _mock.Called(ctx, data, sha256hex)

	if len(ret) == 0 {
		panic("no return value specified for OTAFromData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) error); ok {
		r0 = returnFunc(ctx, data, sha256hex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_OTAFromData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTAFromData'
type Service_OTAFromData_Call struct {
	*mock.Call
}

// OTAFromData is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - sha256hex string
func (_e *Service_Expecter) OTAFromData(ctx interface{}, data interface{}, sha256hex interface{}) *Service_OTAFromData_Call {
	return &Service_OTAFromData_Call{Call: _e.mock.On("OTAFromData", ctx, data, sha256hex)}
}

func (_c *Service_OTAFromData_Call) Run(run func(ctx context.Context, data []byte, sha256hex string)) *Service_OTAFromData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_OTAFromData_Call) Return(err error) *Service_OTAFromData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_OTAFromData_Call) RunAndReturn(run func(ctx context.Context, data []byte, sha256hex string) error) *Service_OTAFromData_Call {
	_c.Call.Return(run)
	return _c
}

// OTAStatus provides a mock function for the type Service
func (_mock *Service) OTAStatus() agent.OTAStatusInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OTAStatus")
	}

	var r0 agent.OTAStatusInfo
	if returnFunc, ok := ret.Get(0).(func() agent.OTAStatusInfo); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agent.OTAStatusInfo)
	}
	return r0
}

// Service_OTAStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTAStatus'
type Service_OTAStatus_Call struct {
	*mock.Call
}

// OTAStatus is a helper method to define mock.On call
func (_e *Service_Expecter) OTAStatus() *Service_OTAStatus_Call {
	return &Service_OTAStatus_Call{Call: _e.mock.On("OTAStatus")}
}

func (_c *Service_OTAStatus_Call) Run(run func()) *Service_OTAStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_OTAStatus_Call) Return(oTAStatusInfo agent.OTAStatusInfo) *Service_OTAStatus_Call {
	_c.Call.Return(oTAStatusInfo)
	return _c
}

func (_c *Service_OTAStatus_Call) RunAndReturn(run func() agent.OTAStatusInfo) *Service_OTAStatus_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDevice provides a mock function for the type Service
func (_mock *Service) OpenDevice(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OpenDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_OpenDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDevice'
type Service_OpenDevice_Call struct {
	*mock.Call
}

// OpenDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Service_Expecter) OpenDevice(ctx interface{}, id interface{}) *Service_OpenDevice_Call {
	return &Service_OpenDevice_Call{Call: _e.mock.On("OpenDevice", ctx, id)}
}

func (_c *Service_OpenDevice_Call) Run(run func(ctx context.Context, id string)) *Service_OpenDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_OpenDevice_Call) Return(err error) *Service_OpenDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_OpenDevice_Call) RunAndReturn(run func(ctx context.Context, id string) error) *Service_OpenDevice_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Service
func (_mock *Service) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Service_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Service_Expecter) Ping() *Service_Ping_Call {
	return &Service_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Service_Ping_Call) Run(run func()) *Service_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Ping_Call) Return(err error) *Service_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Ping_Call) RunAndReturn(run func() error) *Service_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Service
func (_mock *Service) Publish(topic string, payload string) error {
	ret := _mock.Called(topic, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(topic, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Service_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - payload string
func (_e *Service_Expecter) Publish(topic interface{}, payload interface{}) *Service_Publish_Call {
	return &Service_Publish_Call{Call: _e.mock.On("Publish", topic, payload)}
}

func (_c *Service_Publish_Call) Run(run func(topic string, payload string)) *Service_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Publish_Call) Return(err error) *Service_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Publish_Call) RunAndReturn(run func(topic string, payload string) error) *Service_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDevice provides a mock function for the type Service
func (_mock *Service) ReadDevice(id string, n int) ([]byte, error) {
	ret := _mock.Called(id, n)

	if len(ret) == 0 {
		panic("no return value specified for ReadDevice")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]byte, error)); ok {
		return returnFunc(id, n)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []byte); ok {
		r0 = returnFunc(id, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(id, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ReadDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDevice'
type Service_ReadDevice_Call struct {
	*mock.Call
}

// ReadDevice is a helper method to define mock.On call
//   - id string
//   - n int
func (_e *Service_Expecter) ReadDevice(id interface{}, n interface{}) *Service_ReadDevice_Call {
	return &Service_ReadDevice_Call{Call: _e.mock.On("ReadDevice", id, n)}
}

func (_c *Service_ReadDevice_Call) Run(run func(id string, n int)) *Service_ReadDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ReadDevice_Call) Return(bytes []byte, err error) *Service_ReadDevice_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Service_ReadDevice_Call) RunAndReturn(run func(id string, n int) ([]byte, error)) *Service_ReadDevice_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDevice provides a mock function for the type Service
func (_mock *Service) RemoveDevice(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_RemoveDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDevice'
type Service_RemoveDevice_Call struct {
	*mock.Call
}

// RemoveDevice is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) RemoveDevice(id interface{}) *Service_RemoveDevice_Call {
	return &Service_RemoveDevice_Call{Call: _e.mock.On("RemoveDevice", id)}
}

func (_c *Service_RemoveDevice_Call) Run(run func(id string)) *Service_RemoveDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_RemoveDevice_Call) Return(err error) *Service_RemoveDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_RemoveDevice_Call) RunAndReturn(run func(id string) error) *Service_RemoveDevice_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type Service
func (_mock *Service) Reset(ctx context.Context, mode string) error {
	ret := _mock.Called(ctx, mode)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Service_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - mode string
func (_e *Service_Expecter) Reset(ctx interface{}, mode interface{}) *Service_Reset_Call {
	return &Service_Reset_Call{Call: _e.mock.On("Reset", ctx, mode)}
}

func (_c *Service_Reset_Call) Run(run func(ctx context.Context, mode string)) *Service_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Reset_Call) Return(err error) *Service_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Reset_Call) RunAndReturn(run func(ctx context.Context, mode string) error) *Service_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function for the type Service
func (_mock *Service) Route(ctx context.Context, uuid string, cmdStr string) error {
	ret := _mock.Called(ctx, uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type Service_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) Route(ctx interface{}, uuid interface{}, cmdStr interface{}) *Service_Route_Call {
	return &Service_Route_Call{Call: _e.mock.On("Route", ctx, uuid, cmdStr)}
}

func (_c *Service_Route_Call) Run(run func(ctx context.Context, uuid string, cmdStr string)) *Service_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Route_Call) Return(err error) *Service_Route_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Route_Call) RunAndReturn(run func(ctx context.Context, uuid string, cmdStr string) error) *Service_Route_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceConfig provides a mock function for the type Service
func (_mock *Service) ServiceConfig(ctx context.Context, uuid string, cmdStr string) error {
	ret := _mock.Called(ctx, uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for ServiceConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ServiceConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceConfig'
type Service_ServiceConfig_Call struct {
	*mock.Call
}

// ServiceConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) ServiceConfig(ctx interface{}, uuid interface{}, cmdStr interface{}) *Service_ServiceConfig_Call {
	return &Service_ServiceConfig_Call{Call: _e.mock.On("ServiceConfig", ctx, uuid, cmdStr)}
}

func (_c *Service_ServiceConfig_Call) Run(run func(ctx context.Context, uuid string, cmdStr string)) *Service_ServiceConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_ServiceConfig_Call) Return(err error) *Service_ServiceConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ServiceConfig_Call) RunAndReturn(run func(ctx context.Context, uuid string, cmdStr string) error) *Service_ServiceConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function for the type Service
func (_mock *Service) Services() []agent.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []agent.Info
	if returnFunc, ok := ret.Get(0).(func() []agent.Info); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agent.Info)
		}
	}
	return r0
}

// Service_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type Service_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
func (_e *Service_Expecter) Services() *Service_Services_Call {
	return &Service_Services_Call{Call: _e.mock.On("Services")}
}

func (_c *Service_Services_Call) Run(run func()) *Service_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Services_Call) Return(infos []agent.Info) *Service_Services_Call {
	_c.Call.Return(infos)
	return _c
}

func (_c *Service_Services_Call) RunAndReturn(run func() []agent.Info) *Service_Services_Call {
	_c.Call.Return(run)
	return _c
}

// SetRuntimeConfig provides a mock function for the type Service
func (_mock *Service) SetRuntimeConfig(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetRuntimeConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_SetRuntimeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRuntimeConfig'
type Service_SetRuntimeConfig_Call struct {
	*mock.Call
}

// SetRuntimeConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *Service_Expecter) SetRuntimeConfig(ctx interface{}, key interface{}, value interface{}) *Service_SetRuntimeConfig_Call {
	return &Service_SetRuntimeConfig_Call{Call: _e.mock.On("SetRuntimeConfig", ctx, key, value)}
}

func (_c *Service_SetRuntimeConfig_Call) Run(run func(ctx context.Context, key string, value string)) *Service_SetRuntimeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_SetRuntimeConfig_Call) Return(err error) *Service_SetRuntimeConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_SetRuntimeConfig_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *Service_SetRuntimeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type Service
func (_mock *Service) Shutdown() {
	_mock.Called()
	return
}

// Service_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Service_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *Service_Expecter) Shutdown() *Service_Shutdown_Call {
	return &Service_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *Service_Shutdown_Call) Run(run func()) *Service_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Shutdown_Call) Return() *Service_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_Shutdown_Call) RunAndReturn(run func()) *Service_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Telemetry provides a mock function for the type Service
func (_mock *Service) Telemetry() agent.TelemetryData {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Telemetry")
	}

	var r0 agent.TelemetryData
	if returnFunc, ok := ret.Get(0).(func() agent.TelemetryData); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agent.TelemetryData)
	}
	return r0
}

// Service_Telemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Telemetry'
type Service_Telemetry_Call struct {
	*mock.Call
}

// Telemetry is a helper method to define mock.On call
func (_e *Service_Expecter) Telemetry() *Service_Telemetry_Call {
	return &Service_Telemetry_Call{Call: _e.mock.On("Telemetry")}
}

func (_c *Service_Telemetry_Call) Run(run func()) *Service_Telemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Telemetry_Call) Return(telemetryData agent.TelemetryData) *Service_Telemetry_Call {
	_c.Call.Return(telemetryData)
	return _c
}

func (_c *Service_Telemetry_Call) RunAndReturn(run func() agent.TelemetryData) *Service_Telemetry_Call {
	_c.Call.Return(run)
	return _c
}

// Terminal provides a mock function for the type Service
func (_mock *Service) Terminal(uuid string, cmdStr string) error {
	ret := _mock.Called(uuid, cmdStr)

	if len(ret) == 0 {
		panic("no return value specified for Terminal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uuid, cmdStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Terminal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminal'
type Service_Terminal_Call struct {
	*mock.Call
}

// Terminal is a helper method to define mock.On call
//   - uuid string
//   - cmdStr string
func (_e *Service_Expecter) Terminal(uuid interface{}, cmdStr interface{}) *Service_Terminal_Call {
	return &Service_Terminal_Call{Call: _e.mock.On("Terminal", uuid, cmdStr)}
}

func (_c *Service_Terminal_Call) Run(run func(uuid string, cmdStr string)) *Service_Terminal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Terminal_Call) Return(err error) *Service_Terminal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Terminal_Call) RunAndReturn(run func(uuid string, cmdStr string) error) *Service_Terminal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLiveness provides a mock function for the type Service
func (_mock *Service) UpdateLiveness(svcname string, svctype string) error {
	ret := _mock.Called(svcname, svctype)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLiveness")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(svcname, svctype)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_UpdateLiveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLiveness'
type Service_UpdateLiveness_Call struct {
	*mock.Call
}

// UpdateLiveness is a helper method to define mock.On call
//   - svcname string
//   - svctype string
func (_e *Service_Expecter) UpdateLiveness(svcname interface{}, svctype interface{}) *Service_UpdateLiveness_Call {
	return &Service_UpdateLiveness_Call{Call: _e.mock.On("UpdateLiveness", svcname, svctype)}
}

func (_c *Service_UpdateLiveness_Call) Run(run func(svcname string, svctype string)) *Service_UpdateLiveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_UpdateLiveness_Call) Return(err error) *Service_UpdateLiveness_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_UpdateLiveness_Call) RunAndReturn(run func(svcname string, svctype string) error) *Service_UpdateLiveness_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDevice provides a mock function for the type Service
func (_mock *Service) WriteDevice(id string, hexData string) (int, error) {
	ret := _mock.Called(id, hexData)

	if len(ret) == 0 {
		panic("no return value specified for WriteDevice")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return returnFunc(id, hexData)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = returnFunc(id, hexData)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(id, hexData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_WriteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDevice'
type Service_WriteDevice_Call struct {
	*mock.Call
}

// WriteDevice is a helper method to define mock.On call
//   - id string
//   - hexData string
func (_e *Service_Expecter) WriteDevice(id interface{}, hexData interface{}) *Service_WriteDevice_Call {
	return &Service_WriteDevice_Call{Call: _e.mock.On("WriteDevice", id, hexData)}
}

func (_c *Service_WriteDevice_Call) Run(run func(id string, hexData string)) *Service_WriteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_WriteDevice_Call) Return(n int, err error) *Service_WriteDevice_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Service_WriteDevice_Call) RunAndReturn(run func(id string, hexData string) (int, error)) *Service_WriteDevice_Call {
	_c.Call.Return(run)
	return _c
}
