// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTerminalSession creates a new instance of TerminalSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerminalSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerminalSession {
	mock := &TerminalSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TerminalSession is an autogenerated mock type for the Session type
type TerminalSession struct {
	mock.Mock
}

type TerminalSession_Expecter struct {
	mock *mock.Mock
}

func (_m *TerminalSession) EXPECT() *TerminalSession_Expecter {
	return &TerminalSession_Expecter{mock: &_m.Mock}
}

// IsDone provides a mock function for the type TerminalSession
func (_mock *TerminalSession) IsDone() chan bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDone")
	}

	var r0 chan bool
	if returnFunc, ok := ret.Get(0).(func() chan bool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan bool)
		}
	}
	return r0
}

// TerminalSession_IsDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDone'
type TerminalSession_IsDone_Call struct {
	*mock.Call
}

// IsDone is a helper method to define mock.On call
func (_e *TerminalSession_Expecter) IsDone() *TerminalSession_IsDone_Call {
	return &TerminalSession_IsDone_Call{Call: _e.mock.On("IsDone")}
}

func (_c *TerminalSession_IsDone_Call) Run(run func()) *TerminalSession_IsDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TerminalSession_IsDone_Call) Return(boolCh chan bool) *TerminalSession_IsDone_Call {
	_c.Call.Return(boolCh)
	return _c
}

func (_c *TerminalSession_IsDone_Call) RunAndReturn(run func() chan bool) *TerminalSession_IsDone_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type TerminalSession
func (_mock *TerminalSession) Send(p []byte) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TerminalSession_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TerminalSession_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - p []byte
func (_e *TerminalSession_Expecter) Send(p interface{}) *TerminalSession_Send_Call {
	return &TerminalSession_Send_Call{Call: _e.mock.On("Send", p)}
}

func (_c *TerminalSession_Send_Call) Run(run func(p []byte)) *TerminalSession_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TerminalSession_Send_Call) Return(err error) *TerminalSession_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TerminalSession_Send_Call) RunAndReturn(run func(p []byte) error) *TerminalSession_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type TerminalSession
func (_mock *TerminalSession) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TerminalSession_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type TerminalSession_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *TerminalSession_Expecter) Write(p interface{}) *TerminalSession_Write_Call {
	return &TerminalSession_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *TerminalSession_Write_Call) Run(run func(p []byte)) *TerminalSession_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TerminalSession_Write_Call) Return(n int, err error) *TerminalSession_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TerminalSession_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *TerminalSession_Write_Call {
	_c.Call.Return(run)
	return _c
}
