# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 302 /ui/;
    }

    location /ui/assets/ {
        try_files $uri =404;
    }

    location /ui/ {
        try_files $uri $uri/ /ui/index.html;
    }
}
