// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AddFlow provides a mock function for the type Client
func (_mock *Client) AddFlow(flow string) (string, error) {
	ret := _mock.Called(flow)

	if len(ret) == 0 {
		panic("no return value specified for AddFlow")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(flow)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(flow)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_AddFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFlow'
type Client_AddFlow_Call struct {
	*mock.Call
}

// AddFlow is a helper method to define mock.On call
//   - flow string
func (_e *Client_Expecter) AddFlow(flow interface{}) *Client_AddFlow_Call {
	return &Client_AddFlow_Call{Call: _e.mock.On("AddFlow", flow)}
}

func (_c *Client_AddFlow_Call) Run(run func(flow string)) *Client_AddFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_AddFlow_Call) Return(s string, err error) *Client_AddFlow_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_AddFlow_Call) RunAndReturn(run func(flow string) (string, error)) *Client_AddFlow_Call {
	_c.Call.Return(run)
	return _c
}

// DeployFlows provides a mock function for the type Client
func (_mock *Client) DeployFlows(flows string) (string, error) {
	ret := _mock.Called(flows)

	if len(ret) == 0 {
		panic("no return value specified for DeployFlows")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(flows)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(flows)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flows)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_DeployFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployFlows'
type Client_DeployFlows_Call struct {
	*mock.Call
}

// DeployFlows is a helper method to define mock.On call
//   - flows string
func (_e *Client_Expecter) DeployFlows(flows interface{}) *Client_DeployFlows_Call {
	return &Client_DeployFlows_Call{Call: _e.mock.On("DeployFlows", flows)}
}

func (_c *Client_DeployFlows_Call) Run(run func(flows string)) *Client_DeployFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_DeployFlows_Call) Return(s string, err error) *Client_DeployFlows_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_DeployFlows_Call) RunAndReturn(run func(flows string) (string, error)) *Client_DeployFlows_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFlows provides a mock function for the type Client
func (_mock *Client) FetchFlows() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchFlows")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_FetchFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFlows'
type Client_FetchFlows_Call struct {
	*mock.Call
}

// FetchFlows is a helper method to define mock.On call
func (_e *Client_Expecter) FetchFlows() *Client_FetchFlows_Call {
	return &Client_FetchFlows_Call{Call: _e.mock.On("FetchFlows")}
}

func (_c *Client_FetchFlows_Call) Run(run func()) *Client_FetchFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_FetchFlows_Call) Return(s string, err error) *Client_FetchFlows_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_FetchFlows_Call) RunAndReturn(run func() (string, error)) *Client_FetchFlows_Call {
	_c.Call.Return(run)
	return _c
}

// FlowState provides a mock function for the type Client
func (_mock *Client) FlowState() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_FlowState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowState'
type Client_FlowState_Call struct {
	*mock.Call
}

// FlowState is a helper method to define mock.On call
func (_e *Client_Expecter) FlowState() *Client_FlowState_Call {
	return &Client_FlowState_Call{Call: _e.mock.On("FlowState")}
}

func (_c *Client_FlowState_Call) Run(run func()) *Client_FlowState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_FlowState_Call) Return(s string, err error) *Client_FlowState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_FlowState_Call) RunAndReturn(run func() (string, error)) *Client_FlowState_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Client
func (_mock *Client) Ping() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Client_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Client_Expecter) Ping() *Client_Ping_Call {
	return &Client_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Client_Ping_Call) Run(run func()) *Client_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Ping_Call) Return(s string, err error) *Client_Ping_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_Ping_Call) RunAndReturn(run func() (string, error)) *Client_Ping_Call {
	_c.Call.Return(run)
	return _c
}
