File = "/config.toml"
domain_id = "1f0eb7a0-1b50-46c1-a826-6dc695fbce4d"

[channels]
  id = "45f0b998-4118-4420-b602-a57604493ee6"

[heartbeat]
  interval = "10s"

[log]
  level = "info"

[mqtt]
  ca_cert = ""
  ca_path = "ca.crt"
  cert_path = "client.cert"
  client_cert = ""
  client_key = ""
  mtls = false
  password = "687fca0d-00dd-405b-97df-09a4b06a72eb"
  priv_key_path = "client.key"
  qos = 0
  retain = false
  skip_tls_ver = true
  url = "ssl://host.docker.internal:8883"
  username = "3825ef9e-d206-44cb-8797-781cd61ba215"

[nodered]
  url = "http://nodered:1880/"

[server]
  broker_url = "amqp://guest:guest@fluxmq:5682/"
  port = "9999"

[terminal]
  session_timeout = "1m0s"
