File = "/config.toml"
domain_id = "6467ebf8-70a7-4f3b-8626-8ff324e34ec8"

[channels]
  id = "36de88eb-f4bc-45aa-9033-e9540154cd98"

[heartbeat]
  interval = "10s"

[log]
  level = "info"

[mqtt]
  ca_cert = ""
  ca_path = "ca.crt"
  cert_path = "client.cert"
  client_cert = ""
  client_key = ""
  mtls = false
  password = "cef7296a-d87f-42de-8743-de86511f9aa6"
  priv_key_path = "client.key"
  qos = 0
  retain = false
  skip_tls_ver = true
  # Use "ssl://messaging.magistrala.absmach.eu:8883" for Magistrala cloud.
  url = "ssl://host.docker.internal:8883"
  username = "ca5b266d-a0c4-4fd6-a164-c82c9909b7a6"

[nodered]
  url = "http://nodered:1880/"

[server]
  broker_url = "amqp://guest:guest@fluxmq:5682/"
  port = "9999"

[terminal]
  session_timeout = "1m0s"
