File = "/config.toml"
domain_id = "a1c51744-3317-48e2-9eef-4df37f68b9d1"

[channels]
  id = "82f1d080-b1ce-41b7-aef2-62b270e551e7"

[heartbeat]
  interval = "10s"

[log]
  level = "debug"

[mqtt]
  ca_cert = ""
  ca_path = "ca.crt"
  cert_path = "client.cert"
  client_cert = ""
  client_key = ""
  mtls = false
  password = "ec557975-fa05-419d-ba49-4cb07ce73735"
  priv_key_path = "client.key"
  qos = 0
  retain = false
  skip_tls_ver = false
  url = "ssl://messaging.magistrala.absmach.eu:8883"
  username = "91e9aff0-b934-48f9-917c-2524e9f25729"

[nodered]
  url = "http://nodered:1880/"

[server]
  broker_url = "amqp://guest:guest@fluxmq:5682/"
  port = "9999"

[terminal]
  session_timeout = "1m0s"
