// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// FetchConfig provides a mock function for the type Client
func (_mock *Client) FetchConfig(strings []string) (string, error) {
	ret := _mock.Called(strings)

	if len(ret) == 0 {
		panic("no return value specified for FetchConfig")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (string, error)); ok {
		return returnFunc(strings)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) string); ok {
		r0 = returnFunc(strings)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_FetchConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchConfig'
type Client_FetchConfig_Call struct {
	*mock.Call
}

// FetchConfig is a helper method to define mock.On call
//   - strings []string
func (_e *Client_Expecter) FetchConfig(strings interface{}) *Client_FetchConfig_Call {
	return &Client_FetchConfig_Call{Call: _e.mock.On("FetchConfig", strings)}
}

func (_c *Client_FetchConfig_Call) Run(run func(strings []string)) *Client_FetchConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_FetchConfig_Call) Return(s string, err error) *Client_FetchConfig_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_FetchConfig_Call) RunAndReturn(run func(strings []string) (string, error)) *Client_FetchConfig_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMetrics provides a mock function for the type Client
func (_mock *Client) FetchMetrics(cmdArr []string) (string, error) {
	ret := _mock.Called(cmdArr)

	if len(ret) == 0 {
		panic("no return value specified for FetchMetrics")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (string, error)); ok {
		return returnFunc(cmdArr)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) string); ok {
		r0 = returnFunc(cmdArr)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(cmdArr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_FetchMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMetrics'
type Client_FetchMetrics_Call struct {
	*mock.Call
}

// FetchMetrics is a helper method to define mock.On call
//   - cmdArr []string
func (_e *Client_Expecter) FetchMetrics(cmdArr interface{}) *Client_FetchMetrics_Call {
	return &Client_FetchMetrics_Call{Call: _e.mock.On("FetchMetrics", cmdArr)}
}

func (_c *Client_FetchMetrics_Call) Run(run func(cmdArr []string)) *Client_FetchMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_FetchMetrics_Call) Return(s string, err error) *Client_FetchMetrics_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_FetchMetrics_Call) RunAndReturn(run func(cmdArr []string) (string, error)) *Client_FetchMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Client
func (_mock *Client) Ping() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Client_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Client_Expecter) Ping() *Client_Ping_Call {
	return &Client_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Client_Ping_Call) Run(run func()) *Client_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Ping_Call) Return(s string, err error) *Client_Ping_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_Ping_Call) RunAndReturn(run func() (string, error)) *Client_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PushOperation provides a mock function for the type Client
func (_mock *Client) PushOperation(strings []string) (string, error) {
	ret := _mock.Called(strings)

	if len(ret) == 0 {
		panic("no return value specified for PushOperation")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (string, error)); ok {
		return returnFunc(strings)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) string); ok {
		r0 = returnFunc(strings)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_PushOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushOperation'
type Client_PushOperation_Call struct {
	*mock.Call
}

// PushOperation is a helper method to define mock.On call
//   - strings []string
func (_e *Client_Expecter) PushOperation(strings interface{}) *Client_PushOperation_Call {
	return &Client_PushOperation_Call{Call: _e.mock.On("PushOperation", strings)}
}

func (_c *Client_PushOperation_Call) Run(run func(strings []string)) *Client_PushOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_PushOperation_Call) Return(s string, err error) *Client_PushOperation_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_PushOperation_Call) RunAndReturn(run func(strings []string) (string, error)) *Client_PushOperation_Call {
	_c.Call.Return(run)
	return _c
}
